[project]
name = "Project3297"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Laicy0q0", email = "Laicy0q0@connect.hku.hk"},
]
dependencies = ["Django>=6.0.*"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
