# Generated by Django 4.2.29 on 2026-04-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='betatester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BetaTrax.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BetaTrax.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_email', models.CharField(blank=True, max_length=254, null=True)),
                ('version', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('reproduce_step', models.TextField()),
                ('defect_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('CannotReproduce', 'Cannot Reproduce'), ('Fixed', 'Fixed'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Duplicated', 'Duplicated')], default='New', max_length=64)),
                ('severity', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Low', 'Low')], max_length=10, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betatester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='BetaTrax.betatester')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='BetaTrax.developer')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='If this defect is a duplicate, link to the original report.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='BetaTrax.defectreport')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='BetaTrax.product')),
                ('productowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='BetaTrax.productowner')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BetaTrax.defectreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
